// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";
import dotenv from "dotenv"; // Import dotenv
dotenv.config(); // Load .env file

const tables = [
  { name: "example", columns: [] },
  {
    name: "products",
    columns: [
      { name: "name", type: "text" },
      { name: "category", type: "text" },
      { name: "price", type: "float" },
      { name: "description", type: "text" },
      { name: "stock", type: "int" },
      { name: "productId", type: "int", unique: true },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type Example = InferredTypes["example"];
export type ExampleRecord = Example & XataRecord;

export type Products = InferredTypes["products"];
export type ProductsRecord = Products & XataRecord;

export type DatabaseSchema = {
  example: ExampleRecord;
  products: ProductsRecord;
};
const apiKey = process.env.XATA_API_KEY; // Ensure you read from .env file

if (!apiKey) {
  throw new Error("API key is missing. Please add XATA_API_KEY to your .env file.");
}
const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://Melinda-s-workspace-o3ejv4.eu-central-1.xata.sh/db/xata-CRUD",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
